### ISSUE TITLE
Update to 4.8 clears all of my metaboxes

### ISSUE THREAD

**Issue by retober** [rilwis/meta-box#768]
After updating to v4.8 all of the used metaboxes are empty. They are visible an can be edited but every content is gone.

**Comment by funkedgeek** [comment]
Can you post the code you are using please?

**Comment by senlin** [comment]
Same here, update to 4.8.0 destroys all sites that have it installed.

Any existing metabox is empty in the backend and therefore not visible in the frontend. 

Strangest thing is that entries still live in the database

**Comment by rilwis** [comment]
@retober @senlin Do you see any error in PHP or browser console?

Can you please post the code you're using to register meta boxes?

**Comment by rilwis** [comment]
Just added a fix for field ID, which is probably the cause of this problem. (I guess you use field ID with CAPS characters).

**Comment by senlin** [comment]
here you go: https://gist.github.com/senlin/0799aa7f40626c146eb9

**Comment by rilwis** [comment]
@senlin Can you please check with latest code on Github? I've just added a fix.

**Comment by senlin** [comment]
That partly fixes it. I still have an area where the fields don't how up.

It seems to be related to `RWMB_Group_Field`, the error I get is:
`call_user_func() expects parameter 1 to be a valid callback, class 'RWMB_Group_Field' not found in /path/wp-content/plugins/meta-box/inc/meta-box.php on line 353`

On the particular page where it still doesn't work it throws another warning:
Warning: Invalid argument supplied for foreach() in path/wp-content/themes/so80/templates/wp-consultation.php on line 77

The foreach there reads this:

`$wpconsult_group = rwmb_meta( '_SO_wpconsult_group' );
							
							foreach ( $wpconsult_group as $wpconsult_group_item ) {`

**Comment by rilwis** [comment]
Thanks. The 2nd issue seems the same as in #769. I'm going to fix it now.

**Comment by senlin** [comment]
Please keep me posted if you do, so I can test it.

**Comment by rilwis** [comment]
I'm testing on my localhost with your code and it works. Which PHP version are you using?

**Comment by rilwis** [comment]
I think I know the problem.

The 4.8.0 rewrote the helper function which call field's `get_value` function. And the group extension loads its file only in the admin are, thus, it doesn't work in the frontend.

I have uploaded a new version for Group. Please check it.

**Comment by senlin** [comment]
> I'm testing on my localhost with your code and it works.

This type of comment is not really useful. Makes me feel I'm stupid. I have a site with everything running smoothly. I update your plugin which results in my site falling apart. I am so kind to report it and to send you a separate email. On top of that my case is not unique, there are plenty others whose meta fields are also showing nothing.

> Which PHP version are you using?

On that particular site I am running PHP 7

**Comment by senlin** [comment]
With updated Group addon it works better now, although I am now getting an `Undefined index`-Notice for a checkbox field that I'm using in that group.

Code of the output (of same foreach as above):

```
foreach ( $wpconsult_group as $wpconsult_group_item ) {

	$anchor = $wpconsult_group_item['_SO_wpconsult_groupitem_anchor'];
	$icon = $wpconsult_group_item['_SO_wpconsult_groupitem_title_icon'];
	$title = $wpconsult_group_item['_SO_wpconsult_groupitem_title'];
	$descr = $wpconsult_group_item['_SO_wpconsult_groupitem_description'];
	$active = $wpconsult_group_item['_SO_wpconsult_groupitem_active'];
		if ( $active == 1 ) {
			$activeclass = ' active';
		} else {
			$activeclass = '';
		}
    
	echo '<li class="accordion-navigation' . $activeclass . '"><a href="#' . $anchor . '"><i class="fa fa-fw fa-' . $icon . '"></i> ' . $title . '</a>';
	echo '<div id="' . $anchor . '" class="content' . $activeclass . '">' . $descr . '</div></li>';
	
}
```

**Comment by rilwis** [comment]
Sorry for my comment. I didn't mean that. I'm very thankful for your kindness when you reached to me via email to report the bug.

Regarding the bug with undefined index, it seems that the browser doesn't set `$_POST['active']` in the group if it's not checked. More details on that [here](http://stackoverflow.com/questions/11424037/does-input-type-checkbox-only-post-data-if-its-checked). I will find a fix for that soon.

In the meantime, you can use this code:

```php
$active = empty( $wpconsult_group_item['_SO_wpconsult_groupitem_active'] ) ? 0 : 1;
```

**Comment by senlin** [comment]
Thanks, that works.
In regards to the checkbox not being set and since this is a global issue related to checkboxes in general and not to your plugin, it would then probably be better not to use checkboxes at all in groups?

**Comment by rilwis** [comment]
Yes, not using checkbox in groups is a good practice to get rid of this problem. However, I think users still need it sometimes. In the core of Meta Box, I prevent this bug by looping through all fields and then check `$_POST` for their existence. I will probably do the same for group extension.

**Comment by retober** [comment]
Hello, sorry for the late response.
I tried the new update 4.8.1 and the update for the Meta Box Group Extension (1.0.5) now the Meta Boxes aren't empty anymore, but they are not shown on the frontend. Debug is activated but there are no errors. There are multiple Meta Boxes that work fine but they are not using the group functionality so i guess it is a problem with the Meta Box Group Extension.

**Backend Code:**
```<?php
global $meta_boxes;
$prefix = 'Features_';
$args = array( 'taxonomy' => 'product_cat' );
$terms = get_terms('product_cat', $args);
$meta_boxes[] = array(
    'title'  => __( 'Frontpage Features' ),
    'post_types' => array( 'post', 'page' ),
    // MAIN GROUP
    'fields' => array(
      array(
        'id'     => 'features',
        'type'   => 'group',
        'clone'  => true,
        'sort_clone' => true,
        // HALF WIDTH BOX
        'fields' => array (
          // HALF IMAGE
          array (
            'name' => __( 'Großes Bild', 'rwmb' ),
            'id'   => "{$prefix}half_image",
            'max_file_uploads' => 1,
            'type' => 'image_advanced',
          ),
          // TITLE HALF IMAGE
          array (
            'name' => __( 'Großes Bild Titel', 'rwmb' ),
            'id'   => "{$prefix}half_title",
            'type' => 'text',
          ),
          // LINK BELOW HALF IMAGE
          array (
              'name' => __( 'Großes Bild Link', 'rwmb' ),
              'id' => "{$prefix}half_link",
              'type' => 'text',
          ),
          // ROW TITLE
          array (
            'name' => __( 'Schmaller Titel', 'rwmb' ),
            'id'   => "{$prefix}half_row_title",
            'type' => 'text',
          ),
          // ROW TEXT
          array (
            'name' => __( 'Schmaller Text', 'rwmb' ),
            'id'   => "{$prefix}half_row_text",
            'type' => 'wysiwyg',
          ),
          // ROW IMAGE
          array (
            'name' => __( 'Schmalles Bild', 'rwmb' ),
            'id'   => "{$prefix}half_row_image",
            'max_file_uploads' => 1,
            'type' => 'image_advanced',
          ),
        ),
      ),
    ),
);

/**
 * Register meta boxes
 *
 * @return void
 */
function home_register_meta_boxes()
{
	global $meta_boxes;

	// Make sure there's no errors when the plugin is deactivated or during upgrade
	if ( ! class_exists( 'RW_Meta_Box' ) )
		return;

	// Register meta boxes only for some posts/pages
	if ( ! rw_maybe_include() )
		return;

	foreach ( $meta_boxes as $meta_box )
	{
		new RW_Meta_Box( $meta_box );
	}
}

add_action( 'admin_init', 'home_register_meta_boxes' );

/**
 * Check if meta boxes is included
 *
 * @return bool
 */
function rw_maybe_include()
{
	// Include in back-end only
	if ( ! defined( 'WP_ADMIN' ) || ! WP_ADMIN )
		return false;

	// Always include for ajax
	if ( defined( 'DOING_AJAX' ) && DOING_AJAX )
		return true;

	if ( isset( $_GET['post'] ) )
		$post_id = intval( $_GET['post'] );
	elseif ( isset( $_POST['post_ID'] ) )
		$post_id = intval( $_POST['post_ID'] );
	else
		$post_id = false;

	// Check for page template
	$checked_templates = array( 'page-front.php' );

	$template = get_post_meta( $post_id, '_wp_page_template', true );
	if ( in_array( $template, $checked_templates ) )
		return true;

	// If no condition matched
	return false;
}
?>
```
This is the code i'm using to display the content of the metaboxes at the **frontend**:
```
	/* *************************************************************
	* 					HALF FEATURE META GROUP
	************************************************************* */
	$group_values = rwmb_meta( 'features' );
	if ( isset( $group_values ) && !empty( $group_values ) )	{
		foreach ( $group_values as $group_value ) {
			// LEFT SIDE BIG IMAGE WITH OVERLAY
			$FeatureHalfImage = isset( $group_value['Features_half_image'] ) ? $group_value['Features_half_image'] : '';
			$FeatureHalfTitle = isset( $group_value['Features_half_title'] ) ? $group_value['Features_half_title'] : '';
			$FeatureHalfLink = isset( $group_value['Features_half_link'] ) ? $group_value['Features_half_link'] : '';

        	// RIGHT SIDE ROWS WITH TEXT AND IMAGE BELOW
			$FeatureRowTitle = isset( $group_value['Features_half_row_title'] ) ? $group_value['Features_half_row_title'] : '';
			$FeatureRowParagraph = isset( $group_value['Features_half_row_text'] ) ? $group_value['Features_half_row_text'] : '';
			$FeatureRowImage = isset( $group_value['Features_half_row_image'] ) ? $group_value['Features_half_row_image'] : '';

      		// LEFT SIDE
			echo '<div class="row-max ftr">';
				echo '<div class="grid_6 ftr-half ftr-big">';
	      			echo wp_get_attachment_image( $FeatureHalfImage, 'half-width-img' ); // Display the Box
	      			echo '<div class="ftr-big-overlay">';
			            echo '<div class="ftr-big-overlay-title">' . $FeatureHalfTitle . '</div>'; // Display Title of the Box
			            echo '<a class="btn btn-small" href="' . $FeatureHalfLink . '">Anschauen</a>'; // Display Box Paragraph
			echo '</div></div>';

		 	// RIGHT SIDE
            	echo '<div class="grid_6 ftr-half ftr-rows">';
		            echo '<div class="ftr-row">';
		            	echo '<div class="ftr-row-txt">';
			   				echo '<div class="ftr-row-title"><h2>' . $FeatureRowTitle . '</h2></div>'; // Display Title of the Box
			            	echo '<div class="ftr-row-para"><p>' . $FeatureRowParagraph. '<p></div>'; // Display Box Paragraph
		            echo '</div></div>';

		            echo '<div class="ftr-row ftr-row-img">';
		       			echo wp_get_attachment_image( $FeatureRowImage, 'half-width-row-img' ); // Display the Box
	       	echo '</div></div></div>';
       	}
    }
```

These are my installed Plugins:
- Image Regenerate & Select Crop
- Meta Box
- Meta Box Group
- Meta Box Updater
- Post Thumbnail Editor
- What The File
- WooCommerce
- WooCommerce Germanized

**Comment by rilwis** [comment]
Hi,

Please update the code to register meta boxes. This is the old code which doesn't uses `rwmb_meta_boxes` filter to register meta boxes and it's not supported by `rwmb_meta` anymore. Although it works in the admin area, but if you want to make it work in the frontend, you have to use `get_post_meta` instead of the helper function.

**Comment by p2or** [comment]
@rilwis Then the documentation of the meta box group needs to be updated:
https://metabox.io/docs/meta-box-group/

**Comment by rilwis** [comment]
I've just updated the docs:

https://metabox.io/docs/registering-meta-boxes/#section-historical-note
https://metabox.io/docs/get-meta-value/#section-historical-note

This relates to all fields, not only `group`.

Thanks

**Comment by senlin** [comment]
You might want to change `get_post_meat`into `get_post_meta` (**meta** not _meat_)

**Comment by senlin** [comment]
And basically using the `get_post_meta()` function to output the meta data on the frontend is much safer and avoids _frontend dependency_ a term coined by @billerickson in [his article on the topic](http://www.billerickson.net/advanced-custom-fields-frontend-dependency/) in relation with ACF.

**Comment by rilwis** [comment]
That's right.

In addition, if you want to use `get_post_meta()`, then here is [how the value is saved in the database](https://metabox.io/docs/how-post-meta-is-saved-in-the-database/).

**Comment by p2or** [comment]
@rilwis Great! Thanks for updating the docs. Can we also have an update on the demo-files? `better-include.php` and `include-by-ID-or-page-template.php` are deprecated then.

**Comment by rilwis** [comment]
@p2or No problem. I'm not sure how to update the demo files as they're deprecated. All I can say is recommending using the [Include Exclude](https://metabox.io/plugins/meta-box-include-exclude/) extension.

**Comment by p2or** [comment]
@rilwis The following code is working for `include-by-ID-or-page-template.php`. Since `add_filter( 'rwmb_meta_boxes', 'YOURPREFIX_register_meta_boxes' );` already checks wether meta-box is activated, there is no need for `add_action` anymore, right?

```
function YOURPREFIX_register_meta_boxes( $meta_boxes ) {
    
    $prefix = 'rw_';
    $meta_boxes[] = array(
      'id'     => 'any_id',
      'title'  => __( 'Meta Box Title', 'your-prefix' ),
      'post_types' => post,
      'fields' => array(
        // IMAGE UPLOAD
        array(
          'name' => __( 'Your images', 'your-prefix' ),
          'id'   => "{$prefix}img",
          'type' => 'plupload_image',
        ),
      ),
    );

    return $meta_boxes;
}

// Register meta boxes only for some posts/pages
if (rw_maybe_include() === true){
  add_filter( 'rwmb_meta_boxes', 'YOURPREFIX_register_meta_boxes' );
}

function rw_maybe_include()
{
  // Include in back-end only
  if ( ! defined( 'WP_ADMIN' ) || ! WP_ADMIN )
    return false;
  // Always include for ajax
  if ( defined( 'DOING_AJAX' ) && DOING_AJAX )
    return true;
  // Check for post IDs
  $checked_post_IDs = array( 61, 63, 65, 67, 2 );
  if ( isset( $_GET['post'] ) )
    $post_id = intval( $_GET['post'] );
  elseif ( isset( $_POST['post_ID'] ) )
    $post_id = intval( $_POST['post_ID'] );
  else
    $post_id = false;
  $post_id = (int) $post_id;
  if ( in_array( $post_id, $checked_post_IDs ) )
    return true;
  // Check for page template
  $checked_templates = array( 'full-width.php', 'sidebar-page.php' );
  $template = get_post_meta( $post_id, '_wp_page_template', true );
  if ( in_array( $template, $checked_templates ) )
    return true;
  // If no condition matched
  return false;
}

```

**Comment by rilwis** [comment]
@p2or I've just updated the docs with your suggestions. Thanks a lot.

**Comment by p2or** [comment]
@rilwis I didn't expect that, thanks a bunch! :+1:

**Comment by Rhettro** [comment]
I am having the same problem with my website and I am a front end designer. I have no idea what you are both talking about above, I just want an update that fixes the problem. Tried to delete the plugin and had more issues. This is not cool! When will there be an update to fix this problem so I can get on with creating my site and not have to worry about these issues. I need a fix asap. Thank you!

**Comment by Rhettro** [comment]
Nad why would I have to pay for Meta Box Group when I didn't have to pay for it before? And it seems from others that it doesn't fix the problem anyhow.

**Comment by p2or** [comment]
Hi @Rhettro, 

I presume your code looks like @retober's above, right? That's the 'old style' of registering the boxes, so you'll simply need to rewrite your 'registration code'. 

[@retober's code](https://github.com/rilwis/meta-box/issues/768#issuecomment-185731691) adapted:

```php
<?php

add_filter( 'rwmb_meta_boxes', 'FEATURES_register_meta_boxes' );

/**
 * Register meta boxes
 * @param $meta_boxes
 * @return array
 */
function FEATURES_register_meta_boxes( $meta_boxes )
{

  /**
   * Prefix of meta keys (optional)
   * Use underscore (_) at the beginning to make keys hidden
   * Alt.: You also can make prefix empty to disable it
   */
  // Better has an underscore as last sign
  $prefix = 'Features_';
  $meta_boxes[] = array(

    // Meta box title - Will appear at the drag and drop handle bar. Required.
    'title' => __( 'Frontpage Features', 'rwmb' ),

    // Post types, accept custom post types as well - DEFAULT is array('post'). Optional.
    'post_types' => array( 'post', 'page' ),

    'include' => array(
      // include only on template
      'template' => array( 'page-front.php' ),
    ),

    // Where the meta box appear: normal (default), advanced, side. Optional.
    'context' => 'normal',

    // Order of meta box: high (default), low. Optional.
    'priority' => 'high',

    // Auto save: true, false (default). Optional.
    'autosave' => true,

    // List of meta fields
    'fields' => array(
      
      array(
        'id'     => 'features',
        'type'   => 'group',
        'clone'  => true,
        'sort_clone' => true,
        // HALF WIDTH
        'fields' => array (
          // HALF IMAGE
          array (
            'name' => __( 'Grosses Bild', 'rwmb' ),
            'id'   => "{$prefix}half_image",
            'max_file_uploads' => 1,
            'type' => 'image_advanced',
          ),
        ),
      ),
    ), // fields
  ); // array

  return $meta_boxes;
}

?>
```

**Note:** Make sure that your ID's are matching the old ones, then everything should work again. In order to exclude the boxes like @retober, see the updated demo: https://github.com/rilwis/meta-box/blob/master/demo/include-by-ID-or-page-template.php

Does this help?

**Comment by Rhettro** [comment]
I have no clue what you are talking about. When is thew update come out that fixes this? Can I just delete the plug-in? I am using the theme Salem. I really need to finish this up and don’t know code or where to put code.

Thanks!

**Comment by rilwis** [comment]
@Rhettro Can you please try downloading the development version on Github (Download the file [here](https://github.com/rilwis/meta-box/archive/master.zip) and unzip, upload to your host, overwrite old files)? I've just pushed a fix for backward compatibility.

Thanks.
