### ISSUE TITLE
image_advanced not working in WP 4.5 because of updated backbone.js lib

### ISSUE THREAD

**Issue by rene-hermenau** [rilwis/meta-box#812]
Media uploader is opening but selecting an image is just closing the uploader window without returning the image url. I am still debugging this. Maybe you already have a clue about this issue?

**Comment by rene-hermenau** [comment]
I tracked this issue down to the backbone library which is updated in WP 4.5 from backbone v. 1.1.2 to backbone v. 1.2.3

From https://github.com/WordPress/WordPress/commit/4693b251718442ed0903f13326652a4aa529dfcd

* As of Backbone 1.2.0, you can no longer modify the `events` hash or your view's `el` property in `initialize`, so don't try to modify them there. 
* Since Underscore 1.7, Underscore templates no longer accept an initial data object. `_.template` always returns a function now so make sure you use it that way.

I lack on experience on the backbone library so i still have no fix for this.

**Comment by funkedgeek** [comment]
Can you try the most recent commit on github?  I don't know if its related to the changes you listed but I found some wierd bug and made a patch.  Should be working now

**Comment by rene-hermenau** [comment]
@funkedgeek you made my day. That's awesome. Working perfectly! Thanks so much.

Switching from listenTo to on handler already fixed it completely.
Creating initSort was not necessary for this particular case.

I still do not understand  why the handler was removed from listenTo before it could be used but _frame.on is working fine :+1:
